### ISSUE TITLE
Fail to compile?

### ISSUE THREAD

**Issue by xuhdev** [discordianfish/hankie#1]
I tried to run 

    go get github.com/discordianfish/hankie

But I got this error:

    github.com/discordianfish/hankie/hankie.go:62: not enough arguments in call to dockerclient.NewDockerClient
    github.com/discordianfish/hankie/hankie.go:116: cannot use tag (type string) as type *dockerclient.AuthConfig in argument to docker.PullImage
    github.com/discordianfish/hankie/hankie.go:130: not enough arguments in call to docker.RemoveContainer

go version is

    go version go1.4.2 linux/amd64

**Comment by discordianfish** [comment]
Sorry but this project never really worked and I deprecated it. Use something like swarm/kubernetes/nomand.
